language: generic
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=/opt/ghc/$GHCVER/bin:$PATH

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libgirepository1.0-dev

matrix:
  include:
  - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
  - env: GHCVER=8.2.2 STACK_YAML=stack-8.2.yaml

install:
- stack --no-terminal --install-ghc $ARGS test --bench --dry-run || ( \
    stack --no-terminal $ARGS build cabal-install && \
    stack --no-terminal $ARGS solver --update-config)
# Build the dependencies only
- stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
 - stack --no-terminal --install-ghc build
